# Generated by Django 6.0.2 on 2026-02-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='data_source',
            field=models.CharField(default='alpha_vantage', max_length=50),
        ),
        migrations.AddField(
            model_name='price',
            name='ingested_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
